llanguage: php
    sudo: false
    cache:
        directories:
            - $HOME/.composer/cache/files

    env:
        global:
            - PHPUNIT_FLAGS="-v -c ."
            - SYMFONY_DEPRECATIONS_HELPER="max[self]=0"

    matrix:
        fast_finish: true
        include:
            # Minimum supported dependencies with the latest and oldest PHP version
            -   php: 8.0
                env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
            -   php: 7.1
                env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

            # Test the latest stable release
            -   php: 7.1
            -   php: 7.2
            -   php: 8.0
                env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"

            # Latest commit to master.
            -   php: 8.0
                env: STABILITY="dev"

        allow_failures:
            # Dev-master is allowed to fail.
            -   env: STABILITY="dev"

    before_install:
        - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
        - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;

    install:
        - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

    script:
        - composer validate --strict --no-check-lock
        - ./vendor/bin/phpunit $PHPUNIT_FLAGS

notifications:
    email:  [ 'evertharmeling@gmail.com' ]
